name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  UV_SYSTEM_PYTHON: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
          python-version: 3.11
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
    - name: Install requirements
      run: |
          uv pip install -e .[lint,test]
    - uses: pre-commit/action@v3.0.1
    - uses: stefanzweifel/git-auto-commit-action@v6
      if: ${{ inputs.lint }}
      with:
        commit_message: 'style: pre-commit linting fixes'
        add_options: "--no-verify"
