---
name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  HYPOTHESIS_PROFILE: "ci"
  UV_SYSTEM_PYTHON: "true"

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    uses: ./.github/workflows/testing-reusable.yaml
    with:
      python-version: ${{ matrix.python-version }}
      lint: ${{ matrix.python-version == '3.9' }}
